name: RegisterAndLoginPlugin-1.21
<<<<<<< HEAD
version: 1.0.4
=======
version: 1.0.2
>>>>>>> 0c5fda95d35f1942bbb0e2f8c8608d2972b759ba
main: chfeng.ciyueaiwan.registerAndLoginPlugin121.RegisterAndLoginPlugin121
api-version: 1.21
load: STARTUP
authors: ["ciyueaiwan"]
description: 登录注册插件，防止账号被盗
commands:
  register:
    description: 注册账号
    usage: /register <密码> <确认密码>
  login:
    description: 登录账号
    usage: /login <密码>
    aliases: [l]